server:
  port: 8080

spring:
  application:
    name: SecurityApp

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type: trace
        sql: DEBUG
